# Random Forest Classifier

###### import libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
from sklearn import datasets
df_array = datasets.load_breast_cancer()
df = pd.DataFrame(df_array.data,columns=df_array.feature_names)
df.head(2)
#df_breastcanser = pd.DataFrame(breast_cancer_ds.data, columns=breast_cancer_ds.feature_names)

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38           122.8     1001.0          0.11840   
1        20.57         17.77           132.9     1326.0          0.08474   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33            184.6   
1                 0.05667  ...         24.99          23.41            158.8   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  

[2 rows x 30 columns]

In [5]:
# concatenate Target Column to main DF
df['Target'] = df_array['target']

In [6]:
df.head(2)

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38           122.8     1001.0          0.11840   
1        20.57         17.77           132.9     1326.0          0.08474   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33            184.6      2019.0   
1                 0.05667  ...          23.41            158.8      1956.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   

   worst symmetry  worst fractal dimension  Target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  

[2 rows x 31 columns]

In [178]:
# split data in X and y
from sklearn.model_selection import train_test_split
X = df.iloc[: , 0:-1]
print(X.shape)
y = df.iloc[:,-1]
print(y.shape)
X_Train,X_Test,Y_Train,Y_Test = train_test_split(X,y, test_size =.2 , random_state =2)
print('X_Train Shape : ' , X_Train.shape)
print('X_Test Shape : ' , X_Test.shape)
print('Y_Train Shape : ' , Y_Train.shape)
print('Y_Test Shape : ' , Y_Test.shape)


(569, 30)
(569,)
X_Train Shape :  (455, 30)
X_Test Shape :  (114, 30)
Y_Train Shape :  (455,)
Y_Test Shape :  (114,)


###### import libraries

In [171]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression


from sklearn.model_selection import RandomizedSearchCV  # Randomized search on hyper parameters.
from sklearn.model_selection import GridSearchCV    # Exhaustive search over specified parameter values for an estimator.


from sklearn.feature_selection import SelectFromModel # Random Forest : Meta-transformer for selecting features based on importance weights.
from sklearn.feature_selection import RFE # Feature ranking with recursive feature elimination.


from sklearn.model_selection import train_test_split # Split arrays or matrices into random train and test subsets.
from sklearn.metrics import ConfusionMatrixDisplay,accuracy_score,confusion_matrix,precision_score,average_precision_score


dt=DecisionTreeClassifier()
rfc=RandomForestClassifier()
Log_Reg = LogisticRegression()
LR = LinearRegression()

###### Train Random Forest Classifier Model

In [143]:
rfc_model= rfc.fit(X_Train,Y_Train)

In [154]:
rfc_model_predict =rfc_model.predict(X_Test)
print('Random Forest Basic Accuracy : ' , accuracy_score(Y_Test, rfc_model_predict))

Random Forest Basic Accuracy :  0.9473684210526315


###### Getting Important Features

In [114]:
rfc_model.feature_importances_

array([0.02669566, 0.01271754, 0.02895048, 0.06653738, 0.00593579,
       0.00580202, 0.0437243 , 0.10475747, 0.00249277, 0.00385426,
       0.00597997, 0.00388791, 0.01835048, 0.04360752, 0.0038297 ,
       0.00479762, 0.0042188 , 0.00825146, 0.0029303 , 0.00266816,
       0.13807074, 0.01764844, 0.13536739, 0.143239  , 0.00827676,
       0.0059055 , 0.03211364, 0.10912911, 0.00591319, 0.00434666])

In [115]:
rfc_model.feature_importances_.shape

(30,)

In [168]:
#rfc_model.feature_importances_.reshape(6,5)

In [116]:
columns = ['col_names', 'importance']
Feature_importance = pd.DataFrame((rfc_model.feature_importances_) ,columns=['Importance'] )
Feature_importance['Col_names']=X_Test.columns
#mean_ = Feature_importance['Imporance'].mean()
mean= Feature_importance['Importance'].mean()
print('Average of Importance of all Feature : ' , mean)

Average of Importance of all Feature :  0.03333333333333333


In [117]:
above_avg_feature=Feature_importance[Feature_importance['Importance']>mean]
col_list = list[above_avg_feature['Col_names']]
col_list

list[3                mean area
6           mean concavity
7      mean concave points
13              area error
20            worst radius
22         worst perimeter
23              worst area
27    worst concave points
Name: Col_names, dtype: object]

###### Random Forest Classifier on Selected Feature Only

In [142]:
col=['mean area', 'mean concavity','mean concave points','area error','worst radius', 'worst perimeter','worst area','worst concave points']
X_Test_Less = X_Test[col]
X_Train_Less=X_Train[col]
X_Train.shape
X_Test.shape

(114, 8)

In [134]:
sel_feature_rfc = rfc.fit(X_Train,Y_Train)
sel_feature_rfc_predict = sel_feature_rfc.predict(X_Test)

In [165]:
print('Random Forest Basic Accuracy : ' , accuracy_score(Y_Test, sel_feature_rfc_predict))

Random Forest Basic Accuracy :  0.9473684210526315


In [169]:
X_Test.head(2)

mean area  mean concavity  mean concave points  area error  worst radius  \
528      594.2          0.1010              0.06615       44.74         14.62   
291      687.3          0.0594              0.04819       24.87         16.25   

     worst perimeter  worst area  worst concave points  
528            94.52       653.3                0.1015  
291           109.10       809.8                0.1489

In [192]:
from sklearn.feature_selection import RFE # Feature ranking with recursive feature elimination.
selector = RFE(estimator=sel_feature_rfc, n_features_to_select=None, step=1)
selector = selector.fit(X_Train, Y_Train)
selector.support_
#array([ True,  True,  True,  True,  True, False, False, False, False,False])
#selector.ranking_

array([ True,  True,  True,  True, False, False,  True,  True, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True, False, False])

In [231]:
#Imp_Feature['Importance']
#Imp_Feature = pd.DataFrame(X_Test.columns)
col_list = list(X_Test.columns)
col_list
Imp_Feature=pd.DataFrame()
Imp_Feature['Column']=col_list
col_list

['mean radius',
 'mean texture',
 'mean perimeter',
 'mean area',
 'mean smoothness',
 'mean compactness',
 'mean concavity',
 'mean concave points',
 'mean symmetry',
 'mean fractal dimension',
 'radius error',
 'texture error',
 'perimeter error',
 'area error',
 'smoothness error',
 'compactness error',
 'concavity error',
 'concave points error',
 'symmetry error',
 'fractal dimension error',
 'worst radius',
 'worst texture',
 'worst perimeter',
 'worst area',
 'worst smoothness',
 'worst compactness',
 'worst concavity',
 'worst concave points',
 'worst symmetry',
 'worst fractal dimension']

In [259]:
selector.support_[5]

False

In [261]:
imp_col = []
non_imp_col=[]
num = 0
for col in col_list:
    if selector.support_[num]:
        #print('Imp Column : ' , col)
        imp_col.append(col)
    else:
        #print('Non Imp Column : ' , col)
        non_imp_col.append(col)
    num=num+1
print(imp_col)

['mean radius', 'mean texture', 'mean perimeter', 'mean area', 'mean concavity', 'mean concave points', 'area error', 'worst radius', 'worst texture', 'worst perimeter', 'worst area', 'worst smoothness', 'worst compactness', 'worst concavity', 'worst concave points']


In [270]:
rfc_imp_col_X_Test = X_Test[imp_col]
rfc_imp_col_X_Train = X_Train[imp_col]
rfc_imp_col_X_Test.shape

(114, 15)

In [279]:
rfc_rfc_col_model = rfc.fit(rfc_imp_col_X_Train,Y_Train)
rfc_rfc_col_model_predict=rfc.predict(rfc_imp_col_X_Test)
rfc_rfc_col_model_predict
print('Random Forest rfc_Columns Accuracy : ' , accuracy_score(Y_Test, rfc_rfc_col_model_predict))


Random Forest rfc_Columns Accuracy :  0.9473684210526315


In [286]:
# Checking the best estimator of this model

In [287]:
rfc_rfc_col_model.base_estimator_

DecisionTreeClassifier()

In [ ]:
import pandas as pd
from sklearn.ensemble 
import RandomForestClassfier
from sklearn.feature_selection import SelectFromModel
sel = SelectFromModel(RandomForestClassifier(n_estimators = 100))sel.fit(X_train, y_train)
